// The seeded contents of the theme keyword banks (tier 2 of the Keyword
// Bank — see the keyword_theme_banks comment in server/db.js for how
// this relates to the category bank in tier 1).
//
// Seeded editorially rather than mined from the shop's own listings,
// because that's the whole point of this tier: a holiday the shop has
// never listed for has no history to mine, and that's exactly when the
// seller needs the words most. The category bank (tier 1) keeps doing
// the mining job for categories that DO have history.
//
// Slanted toward this shop's actual catalogue (balloons, garlands,
// backdrops, party decor, cake toppers, tableware) rather than generic
// Etsy-wide holiday terms — a keyword that can't plausibly appear on a
// party-supply listing is noise in every prompt it lands in.
//
// weight: 3 = core term, expected on almost any listing for this theme.
//         2 = strong, broadly applicable.
//         1 = long-tail, only when it genuinely fits.
//
// Keywords at 20 characters or fewer AND containing a space are marked
// tag_safe automatically on save (see isTagSafeKeyword in db.js) — the
// longer ones here are deliberate: they're for the title and body, not
// for tags.

const HOLIDAY_BANKS = [
  {
    kind: 'holiday',
    slug: 'halloween',
    label: 'Halloween',
    // Halloween decor selling starts in earnest right after Labor Day;
    // the tail is short because demand collapses on Nov 1.
    windowStart: '09-01',
    windowEnd: '11-01',
    peak: '10-31',
    keywords: [
      { keyword: 'halloween party', weight: 3 },
      { keyword: 'halloween decor', weight: 3 },
      { keyword: 'spooky party', weight: 3 },
      { keyword: 'halloween balloon', weight: 3 },
      { keyword: 'ghost balloon', weight: 2 },
      { keyword: 'pumpkin balloon', weight: 2 },
      { keyword: 'spooky balloon', weight: 2 },
      { keyword: 'bat balloon', weight: 2 },
      { keyword: 'skeleton party', weight: 2 },
      { keyword: 'witch party decor', weight: 2 },
      { keyword: 'haunted house', weight: 2 },
      { keyword: 'trick or treat', weight: 2 },
      { keyword: 'spooky season', weight: 2 },
      { keyword: 'halloween garland', weight: 2 },
      { keyword: 'orange and black', weight: 1 },
      { keyword: 'spider web decor', weight: 1 },
      { keyword: 'creepy cute', weight: 1 },
      { keyword: 'boo party decor', weight: 1 },
      { keyword: 'monster party', weight: 1 },
      { keyword: 'halloween backdrop', weight: 1 },
      { keyword: 'costume party', weight: 1 },
      { keyword: 'pumpkin patch', weight: 1 },
      { keyword: 'halloween birthday party decorations', weight: 1 },
      { keyword: 'first birthday halloween theme', weight: 1 },
    ],
  },
  {
    kind: 'holiday',
    slug: 'thanksgiving',
    label: 'Thanksgiving',
    // Floating (4th Thursday of November) — the window is what matters.
    // Opens as Halloween closes; peak set to the late-November average.
    windowStart: '10-25',
    windowEnd: '11-30',
    peak: '11-26',
    keywords: [
      { keyword: 'thanksgiving decor', weight: 3 },
      { keyword: 'turkey balloon', weight: 3 },
      { keyword: 'thanksgiving party', weight: 3 },
      { keyword: 'friendsgiving', weight: 3 },
      { keyword: 'gobble gobble', weight: 2 },
      { keyword: 'fall table decor', weight: 2 },
      { keyword: 'harvest party', weight: 2 },
      { keyword: 'give thanks decor', weight: 2 },
      { keyword: 'grateful thankful', weight: 2 },
      { keyword: 'thanksgiving table', weight: 2 },
      { keyword: 'autumn party decor', weight: 2 },
      { keyword: 'pumpkin pie party', weight: 1 },
      { keyword: 'cornucopia decor', weight: 1 },
      { keyword: 'turkey day party', weight: 1 },
      { keyword: 'fall garland', weight: 1 },
      { keyword: 'family dinner', weight: 1 },
      { keyword: 'thanksgiving balloon garland kit', weight: 1 },
      { keyword: 'friendsgiving party decorations', weight: 1 },
    ],
  },
  {
    kind: 'holiday',
    slug: 'christmas',
    label: 'Christmas',
    // Opens Nov 1 (the day Halloween demand dies) and closes the day
    // after Christmas, when New Year's takes over.
    windowStart: '11-01',
    windowEnd: '12-26',
    peak: '12-25',
    keywords: [
      { keyword: 'christmas party', weight: 3 },
      { keyword: 'christmas decor', weight: 3 },
      { keyword: 'holiday party', weight: 3 },
      { keyword: 'christmas balloon', weight: 3 },
      { keyword: 'santa balloon', weight: 2 },
      { keyword: 'reindeer balloon', weight: 2 },
      { keyword: 'snowflake decor', weight: 2 },
      { keyword: 'winter wonderland', weight: 2 },
      { keyword: 'christmas garland', weight: 2 },
      { keyword: 'red and green', weight: 2 },
      { keyword: 'holiday backdrop', weight: 2 },
      { keyword: 'christmas tree', weight: 2 },
      { keyword: 'gingerbread party', weight: 1 },
      { keyword: 'candy cane decor', weight: 1 },
      { keyword: 'elf party decor', weight: 1 },
      { keyword: 'snowman balloon', weight: 1 },
      { keyword: 'merry and bright', weight: 1 },
      { keyword: 'nutcracker party', weight: 1 },
      { keyword: 'christmas photo backdrop', weight: 1 },
      { keyword: 'holiday office party decorations', weight: 1 },
    ],
  },
  {
    kind: 'holiday',
    slug: 'new-years',
    label: "New Year's",
    // Wraps the year end: Dec 26 -> Jan 5. isWithinWindow handles it.
    windowStart: '12-26',
    windowEnd: '01-05',
    peak: '01-01',
    keywords: [
      { keyword: 'new years party', weight: 3 },
      { keyword: 'new years eve', weight: 3 },
      { keyword: 'nye party decor', weight: 3 },
      { keyword: 'gold and black', weight: 2 },
      { keyword: 'champagne balloon', weight: 2 },
      { keyword: 'countdown party', weight: 2 },
      { keyword: 'midnight party', weight: 2 },
      { keyword: 'glitter party', weight: 2 },
      { keyword: 'disco party decor', weight: 2 },
      { keyword: 'cheers to party', weight: 1 },
      { keyword: 'confetti balloon', weight: 2 },
      { keyword: 'silver party decor', weight: 1 },
      { keyword: 'sparkle party', weight: 1 },
      { keyword: 'new year balloon', weight: 2 },
      { keyword: 'nye balloon garland kit', weight: 1 },
      { keyword: 'new years eve party decorations', weight: 1 },
    ],
  },
  {
    kind: 'holiday',
    slug: 'valentines',
    label: "Valentine's Day",
    windowStart: '01-06',
    windowEnd: '02-15',
    peak: '02-14',
    keywords: [
      { keyword: 'valentines party', weight: 3 },
      { keyword: 'valentines decor', weight: 3 },
      { keyword: 'heart balloon', weight: 3 },
      { keyword: 'valentines day', weight: 3 },
      { keyword: 'red heart decor', weight: 2 },
      { keyword: 'love party decor', weight: 2 },
      { keyword: 'galentines party', weight: 2 },
      { keyword: 'pink and red', weight: 2 },
      { keyword: 'be mine party', weight: 1 },
      { keyword: 'cupid party', weight: 1 },
      { keyword: 'sweetheart party', weight: 2 },
      { keyword: 'romantic decor', weight: 2 },
      { keyword: 'heart garland', weight: 2 },
      { keyword: 'xoxo party decor', weight: 1 },
      { keyword: 'valentine backdrop', weight: 1 },
      { keyword: 'engagement party', weight: 1 },
      { keyword: 'valentines day party decorations', weight: 1 },
      { keyword: 'heart balloon garland kit', weight: 1 },
    ],
  },
  {
    kind: 'holiday',
    slug: 'st-patricks',
    label: "St. Patrick's Day",
    windowStart: '02-16',
    windowEnd: '03-18',
    peak: '03-17',
    keywords: [
      { keyword: 'st patricks day', weight: 3 },
      { keyword: 'shamrock decor', weight: 3 },
      { keyword: 'lucky party decor', weight: 3 },
      { keyword: 'green party decor', weight: 2 },
      { keyword: 'clover balloon', weight: 2 },
      { keyword: 'irish party', weight: 2 },
      { keyword: 'rainbow party', weight: 2 },
      { keyword: 'pot of gold', weight: 2 },
      { keyword: 'lucky charm', weight: 2 },
      { keyword: 'leprechaun party', weight: 1 },
      { keyword: 'gold coin decor', weight: 1 },
      { keyword: 'shamrock balloon', weight: 2 },
      { keyword: 'green and gold', weight: 1 },
      { keyword: 'lucky one birthday', weight: 1 },
      { keyword: 'st patricks day party decorations', weight: 1 },
    ],
  },
  {
    kind: 'holiday',
    slug: 'fourth-of-july',
    label: 'Fourth of July',
    windowStart: '06-01',
    windowEnd: '07-05',
    peak: '07-04',
    keywords: [
      { keyword: 'fourth of july', weight: 3 },
      { keyword: 'patriotic decor', weight: 3 },
      { keyword: '4th of july', weight: 3 },
      { keyword: 'red white blue', weight: 3 },
      { keyword: 'independence day', weight: 2 },
      { keyword: 'american flag', weight: 2 },
      { keyword: 'star balloon', weight: 2 },
      { keyword: 'usa party decor', weight: 2 },
      { keyword: 'summer bbq party', weight: 2 },
      { keyword: 'firework party', weight: 2 },
      { keyword: 'memorial day', weight: 1 },
      { keyword: 'star spangled', weight: 1 },
      { keyword: 'patriotic balloon', weight: 2 },
      { keyword: 'backyard bbq', weight: 1 },
      { keyword: 'fourth of july party decorations', weight: 1 },
      { keyword: 'patriotic balloon garland kit', weight: 1 },
    ],
  },
  {
    kind: 'holiday',
    slug: 'mothers-day',
    label: "Mother's Day",
    // Floating (2nd Sunday in May); peak is the mid-May average.
    windowStart: '04-10',
    windowEnd: '05-12',
    peak: '05-11',
    keywords: [
      { keyword: 'mothers day gift', weight: 3 },
      { keyword: 'mothers day', weight: 3 },
      { keyword: 'gift for mom', weight: 3 },
      { keyword: 'mom birthday', weight: 2 },
      { keyword: 'floral party decor', weight: 2 },
      { keyword: 'brunch party decor', weight: 2 },
      { keyword: 'best mom ever', weight: 2 },
      { keyword: 'mama balloon', weight: 2 },
      { keyword: 'pink floral decor', weight: 2 },
      { keyword: 'flower balloon', weight: 2 },
      { keyword: 'mom to be', weight: 2 },
      { keyword: 'baby shower decor', weight: 1 },
      { keyword: 'grandma gift', weight: 1 },
      { keyword: 'mothers day party decorations', weight: 1 },
      { keyword: 'mothers day brunch table decor', weight: 1 },
    ],
  },
  {
    kind: 'holiday',
    slug: 'fathers-day',
    label: "Father's Day",
    // Floating (3rd Sunday in June); peak is the mid-June average.
    windowStart: '05-20',
    windowEnd: '06-16',
    peak: '06-15',
    keywords: [
      { keyword: 'fathers day gift', weight: 3 },
      { keyword: 'fathers day', weight: 3 },
      { keyword: 'gift for dad', weight: 3 },
      { keyword: 'dad birthday', weight: 2 },
      { keyword: 'best dad ever', weight: 2 },
      { keyword: 'beer balloon', weight: 2 },
      { keyword: 'bbq party decor', weight: 2 },
      { keyword: 'fishing party', weight: 1 },
      { keyword: 'golf party decor', weight: 1 },
      { keyword: 'dad to be', weight: 2 },
      { keyword: 'grandpa gift', weight: 1 },
      { keyword: 'mens party decor', weight: 1 },
      { keyword: 'papa balloon', weight: 1 },
      { keyword: 'fathers day party decorations', weight: 1 },
      { keyword: 'dads birthday party decor', weight: 1 },
    ],
  },
]

// The everyday fallback. Meteorological season boundaries (Mar/Jun/Sep/
// Dec) rather than astronomical ones — they line up with how party and
// decor buying actually shifts, and they're stable year to year.
// Winter wraps the year end (12-01 -> 02-28).
const SEASON_BANKS = [
  {
    kind: 'season',
    slug: 'spring',
    label: 'Spring',
    windowStart: '03-01',
    windowEnd: '05-31',
    peak: null,
    keywords: [
      { keyword: 'spring party decor', weight: 3 },
      { keyword: 'pastel party', weight: 3 },
      { keyword: 'floral balloon', weight: 3 },
      { keyword: 'garden party', weight: 3 },
      { keyword: 'baby shower decor', weight: 2 },
      { keyword: 'bridal shower', weight: 2 },
      { keyword: 'flower garland', weight: 2 },
      { keyword: 'butterfly party', weight: 2 },
      { keyword: 'pastel balloon', weight: 2 },
      { keyword: 'easter party decor', weight: 2 },
      { keyword: 'bunny party decor', weight: 1 },
      { keyword: 'tea party decor', weight: 2 },
      { keyword: 'blush and gold', weight: 2 },
      { keyword: 'first birthday', weight: 2 },
      { keyword: 'gender reveal', weight: 2 },
      { keyword: 'spring birthday party decorations', weight: 1 },
      { keyword: 'garden tea party backdrop', weight: 1 },
    ],
  },
  {
    kind: 'season',
    slug: 'summer',
    label: 'Summer',
    windowStart: '06-01',
    windowEnd: '08-31',
    peak: null,
    keywords: [
      { keyword: 'summer party decor', weight: 3 },
      { keyword: 'pool party decor', weight: 3 },
      { keyword: 'tropical party', weight: 3 },
      { keyword: 'luau party decor', weight: 2 },
      { keyword: 'beach party decor', weight: 2 },
      { keyword: 'flamingo party', weight: 2 },
      { keyword: 'pineapple decor', weight: 2 },
      { keyword: 'watermelon party', weight: 2 },
      { keyword: 'backyard party', weight: 2 },
      { keyword: 'bbq party decor', weight: 2 },
      { keyword: 'sunshine party', weight: 2 },
      { keyword: 'popsicle party', weight: 1 },
      { keyword: 'mermaid party', weight: 2 },
      { keyword: 'under the sea', weight: 2 },
      { keyword: 'graduation party', weight: 2 },
      { keyword: 'summer birthday party decorations', weight: 1 },
      { keyword: 'tropical pool party backdrop', weight: 1 },
    ],
  },
  {
    kind: 'season',
    slug: 'fall',
    label: 'Fall',
    windowStart: '09-01',
    windowEnd: '11-30',
    peak: null,
    keywords: [
      { keyword: 'fall party decor', weight: 3 },
      { keyword: 'autumn party', weight: 3 },
      { keyword: 'pumpkin decor', weight: 3 },
      { keyword: 'harvest decor', weight: 2 },
      { keyword: 'rust and orange', weight: 2 },
      { keyword: 'boho fall decor', weight: 2 },
      { keyword: 'sunflower party', weight: 2 },
      { keyword: 'woodland party', weight: 2 },
      { keyword: 'little pumpkin', weight: 2 },
      { keyword: 'fall baby shower', weight: 2 },
      { keyword: 'apple party decor', weight: 1 },
      { keyword: 'cozy fall party', weight: 1 },
      { keyword: 'burnt orange', weight: 2 },
      { keyword: 'fall garland', weight: 2 },
      { keyword: 'first birthday', weight: 1 },
      { keyword: 'fall birthday party decorations', weight: 1 },
      { keyword: 'pumpkin first birthday backdrop', weight: 1 },
    ],
  },
  {
    kind: 'season',
    slug: 'winter',
    label: 'Winter',
    // Wraps the year end.
    windowStart: '12-01',
    windowEnd: '02-28',
    peak: null,
    keywords: [
      { keyword: 'winter party decor', weight: 3 },
      { keyword: 'winter wonderland', weight: 3 },
      { keyword: 'snowflake decor', weight: 3 },
      { keyword: 'blue and silver', weight: 2 },
      { keyword: 'cozy party decor', weight: 2 },
      { keyword: 'hot cocoa party', weight: 2 },
      { keyword: 'polar bear party', weight: 1 },
      { keyword: 'penguin party', weight: 1 },
      { keyword: 'snow party decor', weight: 2 },
      { keyword: 'icy blue decor', weight: 2 },
      { keyword: 'winter birthday', weight: 2 },
      { keyword: 'winter onederland', weight: 2 },
      { keyword: 'frozen party decor', weight: 2 },
      { keyword: 'white and silver', weight: 2 },
      { keyword: 'ski party decor', weight: 1 },
      { keyword: 'winter birthday party decorations', weight: 1 },
      { keyword: 'winter onederland first birthday', weight: 1 },
    ],
  },
]

const ALL_THEME_BANKS = [...HOLIDAY_BANKS, ...SEASON_BANKS]

export { HOLIDAY_BANKS, SEASON_BANKS, ALL_THEME_BANKS }
